# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../downloadYoutube.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 276)
        self.mainWidget = QtWidgets.QWidget(MainWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.mainWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainVLayout = QtWidgets.QVBoxLayout()
        self.mainVLayout.setObjectName("mainVLayout")
        self.vLayoutURL = QtWidgets.QVBoxLayout()
        self.vLayoutURL.setObjectName("vLayoutURL")
        self.hLayoutURL = QtWidgets.QHBoxLayout()
        self.hLayoutURL.setObjectName("hLayoutURL")
        self.labelURL = QtWidgets.QLabel(self.mainWidget)
        self.labelURL.setObjectName("labelURL")
        self.hLayoutURL.addWidget(self.labelURL)
        self.lineEditURL = QtWidgets.QLineEdit(self.mainWidget)
        self.lineEditURL.setObjectName("lineEditURL")
        self.hLayoutURL.addWidget(self.lineEditURL)
        self.vLayoutURL.addLayout(self.hLayoutURL)
        self.mainVLayout.addLayout(self.vLayoutURL)
        self.vLayoutPath = QtWidgets.QVBoxLayout()
        self.vLayoutPath.setObjectName("vLayoutPath")
        self.hLayoutPath = QtWidgets.QHBoxLayout()
        self.hLayoutPath.setObjectName("hLayoutPath")
        self.labelPat = QtWidgets.QLabel(self.mainWidget)
        self.labelPat.setObjectName("labelPat")
        self.hLayoutPath.addWidget(self.labelPat)
        self.lineEditPath = QtWidgets.QLineEdit(self.mainWidget)
        self.lineEditPath.setObjectName("lineEditPath")
        self.hLayoutPath.addWidget(self.lineEditPath)
        self.btnSearchPath = QtWidgets.QPushButton(self.mainWidget)
        self.btnSearchPath.setObjectName("btnSearchPath")
        self.hLayoutPath.addWidget(self.btnSearchPath)
        self.vLayoutPath.addLayout(self.hLayoutPath)
        self.mainVLayout.addLayout(self.vLayoutPath)
        self.rBtnMusic = QtWidgets.QRadioButton(self.mainWidget)
        self.rBtnMusic.setObjectName("rBtnMusic")
        self.mainVLayout.addWidget(self.rBtnMusic)
        self.rBtnVideo = QtWidgets.QRadioButton(self.mainWidget)
        self.rBtnVideo.setObjectName("rBtnVideo")
        self.mainVLayout.addWidget(self.rBtnVideo)
        self.downloadButton = QtWidgets.QPushButton(self.mainWidget)
        self.downloadButton.setObjectName("downloadButton")
        self.mainVLayout.addWidget(self.downloadButton)
        self.vLayoutProgress = QtWidgets.QVBoxLayout()
        self.vLayoutProgress.setObjectName("vLayoutProgress")
        self.labelProgress = QtWidgets.QLabel(self.mainWidget)
        self.labelProgress.setObjectName("labelProgress")
        self.vLayoutProgress.addWidget(self.labelProgress)
        self.progressBar = QtWidgets.QProgressBar(self.mainWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.vLayoutProgress.addWidget(self.progressBar)
        self.mainVLayout.addLayout(self.vLayoutProgress)
        self.gridLayout.addLayout(self.mainVLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.mainWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelURL.setText(_translate("MainWindow", "TextLabel"))
        self.labelPat.setText(_translate("MainWindow", "TextLabel"))
        self.btnSearchPath.setText(_translate("MainWindow", "PushButton"))
        self.rBtnMusic.setText(_translate("MainWindow", "RadioButton"))
        self.rBtnVideo.setText(_translate("MainWindow", "RadioButton"))
        self.downloadButton.setText(_translate("MainWindow", "PushButton"))
        self.labelProgress.setText(_translate("MainWindow", "TextLabel"))
